/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visual;

import javax.swing.JDialog;

/**
 *
 * @author Syllas Braga_
 */
public class FormPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FormaPrincipal
     */
    public FormPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        MenuPrincipal = new javax.swing.JMenuBar();
        MenuLogin = new javax.swing.JMenu();
        LoginADM = new javax.swing.JMenuItem();
        LoginESPEC = new javax.swing.JMenuItem();
        LoginJOGADOR = new javax.swing.JMenuItem();
        LoginTECNICO = new javax.swing.JMenuItem();
        MenuCadastro = new javax.swing.JMenu();
        CadEspec = new javax.swing.JMenuItem();
        CadJogador = new javax.swing.JMenuItem();
        CadTecnico = new javax.swing.JMenuItem();

        jToolBar1.setRollover(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Estádio de E-SPORTS");
        setAlwaysOnTop(true);
        setName("FramePrincipal"); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        MenuLogin.setText("Login");

        LoginADM.setText("Administrador");
        LoginADM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginADMActionPerformed(evt);
            }
        });
        MenuLogin.add(LoginADM);

        LoginESPEC.setText("Espectador");
        MenuLogin.add(LoginESPEC);

        LoginJOGADOR.setText("Jogador");
        LoginJOGADOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginJOGADORActionPerformed(evt);
            }
        });
        MenuLogin.add(LoginJOGADOR);

        LoginTECNICO.setText("Técnico");
        MenuLogin.add(LoginTECNICO);

        MenuPrincipal.add(MenuLogin);

        MenuCadastro.setText("Cadastro");

        CadEspec.setText("Espectador");
        CadEspec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadEspecActionPerformed(evt);
            }
        });
        MenuCadastro.add(CadEspec);

        CadJogador.setText("Jogador");
        CadJogador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadJogadorActionPerformed(evt);
            }
        });
        MenuCadastro.add(CadJogador);

        CadTecnico.setText("Técnico");
        CadTecnico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadTecnicoActionPerformed(evt);
            }
        });
        MenuCadastro.add(CadTecnico);

        MenuPrincipal.add(MenuCadastro);

        setJMenuBar(MenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginADMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginADMActionPerformed
        
    }//GEN-LAST:event_LoginADMActionPerformed

    private void LoginJOGADORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginJOGADORActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginJOGADORActionPerformed

    private void CadTecnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadTecnicoActionPerformed
        FormCadAdmEQP form = new FormCadAdmEQP (this,true);
        form.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        form.setTitle("Cadastro de Técnicos");
        form.setLocationRelativeTo(null);
        form.setResizable(false);
        form.setVisible(true);
    }//GEN-LAST:event_CadTecnicoActionPerformed

    private void CadEspecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadEspecActionPerformed
        FormCadESPEC form = new FormCadESPEC(this,true);
        form.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        form.setTitle("Cadastro de Espectadores");
        form.setLocationRelativeTo(null);
        form.setResizable(false);
        form.setVisible(true);
        
    }//GEN-LAST:event_CadEspecActionPerformed

    private void CadJogadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadJogadorActionPerformed
        FormCadJogador form = new FormCadJogador (this,true);
        form.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        form.setTitle("Cadastro de Jogadores");
        form.setLocationRelativeTo(null);
        form.setResizable(false);
        form.setVisible(true);
    }//GEN-LAST:event_CadJogadorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new FormPrincipal().setVisible(true);
                FormPrincipal form = new FormPrincipal();
                form.setLocationRelativeTo(null);
                form.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CadEspec;
    private javax.swing.JMenuItem CadJogador;
    private javax.swing.JMenuItem CadTecnico;
    private javax.swing.JMenuItem LoginADM;
    private javax.swing.JMenuItem LoginESPEC;
    private javax.swing.JMenuItem LoginJOGADOR;
    private javax.swing.JMenuItem LoginTECNICO;
    private javax.swing.JMenu MenuCadastro;
    private javax.swing.JMenu MenuLogin;
    private javax.swing.JMenuBar MenuPrincipal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
